### ISSUE TITLE
Windows 7 installation problem

### ISSUE THREAD

**Issue by ghost** [paulbible/ggtk#1]
Hi,

First I tried execute the command,  it asked me 
python setup.py build
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++
Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

so I tried with  Microsoft Visual C++ 14.0 installed
C:\Python27\python>python setup.py build
then it shows

running build
running build_py
running build_ext
building 'ggtk._go_enums' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD -I../ -IC:\Python27\boost_1_64_0 -IC:\Users\User
\Anaconda3\include -IC:\Users\User\Anaconda3\include "-IC:\Program Files (x86)\M
icrosoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\8
.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\
Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpext/go_enums_wrap.c
xx /Fobuild\temp.win-amd64-3.5\Release\ext/go_enums_wrap.obj /EHsc /DHUNSPELL_ST
ATIC /O2
go_enums_wrap.cxx
c:\users\user\anaconda3\include\pyconfig.h(68): fatal error C1083: Cannot open i
nclude file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\
x86_amd64\\cl.exe' failed with exit status 2

So I checked which is the compatible compiler for python2.7, 
https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_9.0_standalone:_Visual_C.2B-.2B-_Compiler_for_Python_2.7_.28x86.2C_x64.29
they have mentioned 

Visual C++ version 9.0 | 2.6, 2.7, 3.0, 3.1, 3.2,

I tried to download from Microsoft website, but that is not in their list.  Since it's older and I need to pay for that to get that version. If that doesn't compatible afterwards because the first error message said "Microsoft Visual C++ 14.0 is required" that's why I avoid that.

so what are you prefer go with which visual c++ compiler version 14 or version 9(https://www.visualstudio.com/vs/older-downloads/ but that is not a free software)

But in https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_9.0_standalone:_Visual_C.2B-.2B-_Compiler_for_Python_2.7_.28x86.2C_x64.29
have mentioned VCForPython27.msi which is Microsoft Visual C++ Compiler for Python 2.7.
https://www.microsoft.com/en-us/download/details.aspx?id=44266

so my suggestion is, if you make  using VCForPython27.msi  to install ggtk tool in windows,
it doesn't have these type of issues. And there is another constraint I download boost_1_64_0 and I set the variable, is that a problem?

Thankyou,
A.Nishanth

**Comment by paulbible** [comment]
I was able to fine the Microsoft compiler for Python 2.7 at https://www.microsoft.com/en-us/download/details.aspx?id=44266
