### ISSUE TITLE
Unix platform installation issue

### ISSUE THREAD

**Issue by ghost** [paulbible/ggtk#2]
Hi,
I tried with Ubuntu-16.04.3 with python 2.7 and boost1_64_0 and encountered error like this, please help me to install in the unix platform.
The error is attached below
Thankyou,
A.Nishanth

bio_info@BioInfolab:~/ggtk-master/python$ python setup.py build
running build
running build_py
running build_ext
building 'ggtk._go_enums' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../ -I/home/bio_info/boost_1_64_0 -I/usr/include/python2.7 -c ext/go_enums_wrap.cxx -o build/temp.linux-x86_64-2.7/ext/go_enums_wrap.o -O3 -g0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ext/go_enums_wrap.cxx:2854:13: error: ‘ptrdiff_t’ does not name a type
     virtual ptrdiff_t distance(const SwigPyIterator &/*x*/) const
             ^
ext/go_enums_wrap.cxx:2891:21: error: expected ‘;’ at end of member declaration
     SwigPyIterator *advance(ptrdiff_t n)
                     ^
ext/go_enums_wrap.cxx:2891:39: error: expected ‘)’ before ‘n’
     SwigPyIterator *advance(ptrdiff_t n)
                                       ^
ext/go_enums_wrap.cxx:2906:34: error: declaration of ‘operator+=’ as non-function
     SwigPyIterator& operator += (ptrdiff_t n)
                                  ^
ext/go_enums_wrap.cxx:2906:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator& operator += (ptrdiff_t n)
                              ^
ext/go_enums_wrap.cxx:2906:44: error: expected ‘)’ before ‘n’
     SwigPyIterator& operator += (ptrdiff_t n)
                                            ^
ext/go_enums_wrap.cxx:2911:34: error: declaration of ‘operator-=’ as non-function
     SwigPyIterator& operator -= (ptrdiff_t n)
                                  ^
ext/go_enums_wrap.cxx:2911:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator& operator -= (ptrdiff_t n)
                              ^
ext/go_enums_wrap.cxx:2911:44: error: expected ‘)’ before ‘n’
     SwigPyIterator& operator -= (ptrdiff_t n)
                                            ^
ext/go_enums_wrap.cxx:2916:33: error: declaration of ‘operator+’ as non-function
     SwigPyIterator* operator + (ptrdiff_t n) const
                                 ^
ext/go_enums_wrap.cxx:2916:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator* operator + (ptrdiff_t n) const
                              ^
ext/go_enums_wrap.cxx:2916:43: error: expected ‘)’ before ‘n’
     SwigPyIterator* operator + (ptrdiff_t n) const
                                           ^
ext/go_enums_wrap.cxx:2921:33: error: declaration of ‘operator-’ as non-function
     SwigPyIterator* operator - (ptrdiff_t n) const
                                 ^
ext/go_enums_wrap.cxx:2921:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator* operator - (ptrdiff_t n) const
                              ^
ext/go_enums_wrap.cxx:2921:43: error: expected ‘)’ before ‘n’
     SwigPyIterator* operator - (ptrdiff_t n) const
                                           ^
ext/go_enums_wrap.cxx:2926:5: error: ‘ptrdiff_t’ does not name a type
     ptrdiff_t operator - (const SwigPyIterator& x) const
     ^
ext/go_enums_wrap.cxx:3082:23: error: ‘SWIG_From_ptrdiff_t’ declared as an ‘inline’ variable
 SWIG_From_ptrdiff_t  (ptrdiff_t value)
                       ^
ext/go_enums_wrap.cxx:3082:23: error: ‘ptrdiff_t’ was not declared in this scope
ext/go_enums_wrap.cxx:3082:23: note: suggested alternatives:
In file included from /usr/include/c++/5/exception:37:0,
                 from /usr/include/c++/5/stdexcept:38,
                 from ext/go_enums_wrap.cxx:2737:
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:197:28: note:   ‘std::ptrdiff_t’
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:197:28: note:   ‘std::ptrdiff_t’
ext/go_enums_wrap.cxx:3083:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {    
 ^
ext/go_enums_wrap.cxx:3135:39: error: ‘ptrdiff_t’ has not been declared
 SWIG_AsVal_ptrdiff_t (PyObject * obj, ptrdiff_t *val)
                                       ^
ext/go_enums_wrap.cxx: In function ‘int SWIG_AsVal_ptrdiff_t(PyObject*, int*)’:
ext/go_enums_wrap.cxx:3139:50: error: ‘ptrdiff_t’ does not name a type
   if (SWIG_IsOK(res) && val) *val = static_cast< ptrdiff_t >(v);
                                                  ^
ext/go_enums_wrap.cxx: At global scope:
ext/go_enums_wrap.cxx:3495:15: error: ‘swig::check_index’ declared as an ‘inline’ variable
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
               ^
ext/go_enums_wrap.cxx:3495:15: error: ‘ptrdiff_t’ was not declared in this scope
ext/go_enums_wrap.cxx:3495:15: note: suggested alternatives:
In file included from /usr/include/c++/5/exception:37:0,
                 from /usr/include/c++/5/stdexcept:38,
                 from ext/go_enums_wrap.cxx:2737:
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:197:28: note:   ‘std::ptrdiff_t’
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:197:28: note:   ‘std::ptrdiff_t’
ext/go_enums_wrap.cxx:3495:35: error: expected primary-expression before ‘size’
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                   ^
ext/go_enums_wrap.cxx:3495:41: error: expected primary-expression before ‘bool’
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                         ^
ext/go_enums_wrap.cxx:3495:60: error: expression list treated as compound expression in initializer [-fpermissive]
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                                            ^
ext/go_enums_wrap.cxx:3495:62: error: expected ‘,’ or ‘;’ before ‘{’ token
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                                              ^
ext/go_enums_wrap.cxx:11981:1: error: expected ‘}’ at end of input
 }
 ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by paulbible** [comment]
Hi A.Nishanth my sincere apologies. I have not been receiving notifications about these issues. I will take a look.

Can you send the output of 'python -V' and 'gcc -v'?
